services:
  service-pg:
    image: bitnami/postgresql
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: connect
    ports:
      - "5433:5432"
  service-redis:
    image: bitnami/redis
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
